name: PR

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/check.yaml

  osv-scan:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.3.5
    permissions:
      actions: read
      contents: read
      security-events: write
      pull-requests: write
